### ISSUE TITLE
crashes Rhythmbox on Arch Linux when activated

### ISSUE THREAD

**Issue by gavsiu** [fossfreedom/radio-browser#17]
Activating this plugin crashes on Arch Linux and prevents it from opening until I uninstall it.
Installed with sudo make install.

**Comment by fossfreedom** [comment]
At a guess arch move to GTK+3.20 has broken the plugin.

Sorry - I'm not using a GTK+3.20 distro.

Feel free to dig in to fix.

To give you a hint - run rhythmbox in a terminal to see what error messages are displayed.

Run rhythmbox in debug mode and see approximately which line in the code is causing the issue.

rhythmbox -d

**Comment by wagafo** [comment]
This plugin is crasshing Rhythmbox in my system. The steps to reproduce are:

1)  Put rhythmbox to play a podcast, and minimize rhythmbox so that it gets to the background
2) You have to wait until the podcast finishes, pausing it or stopping it does not cause the bug, so suppose the podcast finishes.
3) Click on the appindicator to reopen rhythmbox: it does not open and it crashes.

Please see:
https://bugs.launchpad.net/ubuntu/+source/rhythmbox/+bug/1578260
There is a stacktrace there in case it may be useful.

My system:
Description:	Ubuntu 16.04 LTS
Release:	16.04
